# Generated by Django 4.2.11 on 2026-10-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="rental_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
