# Generated by Django 4.2.11 on 2026-10-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffprofile",
            name="role_name",
            field=models.CharField(
                choices=[
                    ("system_owner", "System Owner"),
                    ("main_admin", "Main Admin"),
                    ("kyc_reviewer", "KYC Reviewer"),
                    ("property_reviewer", "Property Reviewer"),
                    ("support", "Customer Support"),
                    ("financial_approver", "Financial Approver"),
                    ("psp_reconciliation", "PSP Reconciliation"),
                    ("payout_operator", "Payout Operator"),
                    ("refund_operator", "Refund Operator"),
                    ("dispute_resolver", "Dispute Resolver"),
                ],
                db_index=True,
                default="kyc_reviewer",
                max_length=50,
                verbose_name="Role Name",
            ),
        ),
    ]
