# Generated by Django 4.2.11 on 2026-10-10 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0020_propertyvisit_accepted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=150)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("placement", models.CharField(default="tenant_home", max_length=40)),
                ("offer_id", models.CharField(blank=True, default="", max_length=64)),
                ("plan_snapshot", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "starts_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("ends_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AdvertisingPlan",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_en", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                (
                    "duration_unit",
                    models.CharField(
                        choices=[
                            ("week", "Week"),
                            ("calendar_month", "Calendar month"),
                            ("calendar_year", "Calendar year"),
                        ],
                        max_length=20,
                    ),
                ),
                ("duration_count", models.PositiveSmallIntegerField(default=1)),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                ("revision", models.CharField(default="1", max_length=32)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="MockAdvertisementPayment",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_id", models.CharField(max_length=160)),
                ("payment_mode", models.CharField(default="mock", max_length=20)),
                ("status", models.CharField(default="mock_succeeded", max_length=30)),
                (
                    "advertisement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="advertising.advertisement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AdvertisementOperation",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_id", models.CharField(max_length=128)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("found", "Found"),
                            ("rejected", "Rejected"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payload_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("retry_allowed", models.BooleanField(default=False)),
                ("rejection_errors", models.JSONField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertisement_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdvertisementMedia",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("banner", models.FileField(upload_to="advertising/banner_ads/%Y/%m/")),
                ("sha256", models.CharField(max_length=64)),
                ("content_type", models.CharField(max_length=32)),
                ("size_bytes", models.PositiveBigIntegerField()),
                (
                    "advertisement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="advertising.advertisement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="advertisement",
            name="operation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advertisement",
                to="advertising.advertisementoperation",
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advertisements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="advertisements",
                to="properties.property",
            ),
        ),
        migrations.AddConstraint(
            model_name="advertisementoperation",
            constraint=models.UniqueConstraint(
                fields=("owner", "operation_id"), name="unique_ad_operation_per_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="advertisement",
            index=models.Index(
                fields=["placement", "status", "starts_at", "ends_at"],
                name="advertising_public_feed_idx",
            ),
        ),
    ]
