name: aait_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  watcher: ^1.2.1


workspace:
  - packages/core
  - apps/sokoun_app
  - apps/landing_page


dev_dependencies:
  melos: ^8.0.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

melos:
  scripts:
    analyze:
      run: melos exec -- dart analyze .
      description: تحليل كل الـ packages
    test:
      run: melos exec -- flutter test
      description: تشغيل التستات
    gen:
      run: melos exec -- dart run build_runner build -d
      description: codegen للـ injectable/json
    translations:
      run: dart run generate/strings/main.dart
      description: generate translation files
    translations_watch:
      run: dart run generate/strings/main.dart --watch
      description: watch and generate translation files
    clean:
      run: melos exec -- flutter clean
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
flutter_assets_generator:
  output_dir: generated/
  output_filename: assets
  class_name: Assets
  auto_detection: true
  # Automatically add missing dependencies (rive, flutter_svg, lottie) default: true
  auto_add_dependencies: true
  # Options: robust (default), legacy (old style)
  style: robust
  package_parameter_enabled: false
  named_with_parent: true
  path_ignore: [ ]
