# Generated by Django 4.2.11 on 2026-09-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="notificatio_user_id_f0e72c_idx",
            old_name="devtok_user_active_idx",
        ),
        migrations.RenameIndex(
            model_name="devicetoken",
            new_name="notificatio_token_1a2c49_idx",
            old_name="devtok_token_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_427e4b_idx",
            old_name="notif_user_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_05b4bc_idx",
            old_name="notif_user_created_idx",
        ),
    ]
