# Generated by Django 4.2.11 on 2026-10-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("visit_request", "Visit Request"),
                    ("visit_accepted", "Visit Accepted"),
                    ("visit_rejected", "Visit Rejected"),
                    ("new_message", "New Message"),
                    ("property_update", "Property Update"),
                    ("property_verified", "Property Verified"),
                    ("property_views", "Property Views"),
                    ("daily_bump", "Daily Bump"),
                    ("new_property", "New Property In Area"),
                    ("security_alert", "Security Alert"),
                    ("account_verification", "Account Verification"),
                    ("visit_review", "Visit Review"),
                    ("promotion", "Promotion"),
                    ("general", "General Notification"),
                    ("tenancy_invitation", "Tenancy Invitation"),
                    ("tenancy_invitation_response", "Tenancy Invitation Response"),
                    ("rental_interest", "Rental Interest"),
                    ("rental_terms", "Rental Terms"),
                    ("rental_agreement", "Rental Agreement"),
                    ("rental_handover", "Rental Handover"),
                    ("rental_evidence", "Rental Evidence"),
                    ("rental_deposit", "Rental Deposit"),
                    ("rental_payout", "Rental Payout"),
                ],
                default="general",
                max_length=50,
                verbose_name="Notification Type",
            ),
        ),
    ]
