# Generated by Django 4.2.11 on 2026-10-08 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0019_remove_savedproperty_unique_saved_property_and_more"),
        ("features", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenancyInvitation",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("offer_id", models.CharField(blank=True, default="", max_length=64)),
                ("offer_snapshot", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AlterModelOptions(
            name="lease",
            options={"ordering": ["-created_at", "-updated_at"]},
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["draft", "pending", "signed", "active"])
                ),
                fields=("property", "offer_id"),
                name="unique_live_lease_per_accommodation",
            ),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="initiated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initiated_tenancy_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="lease",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenancy_invitation",
                to="features.lease",
            ),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_tenancy_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tenancy_invitations",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responded_tenancy_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="received_tenancy_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="tenancyinvitation",
            index=models.Index(
                fields=["owner", "-created_at"], name="invite_owner_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenancyinvitation",
            index=models.Index(
                fields=["tenant", "-created_at"], name="invite_tenant_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tenancyinvitation",
            index=models.Index(
                fields=["property", "offer_id", "status"], name="invite_eligibility_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenancyinvitation",
            constraint=models.CheckConstraint(
                check=models.Q(("owner", models.F("tenant")), _negated=True),
                name="invitation_participants_distinct",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenancyinvitation",
            constraint=models.CheckConstraint(
                check=models.Q(("revision__gte", 1)),
                name="invitation_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tenancyinvitation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("lease__isnull", True), ("status__in", ["pending", "accepted"])
                ),
                fields=("owner", "property", "tenant", "offer_id"),
                name="unique_live_tenancy_invitation",
            ),
        ),
    ]
