# Generated by Django 4.2.11 on 2026-10-09 16:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("features", "0002_tenancyinvitation_alter_lease_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="idempotencyrecord",
            name="is_rental_operation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="recovery_status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("pending", "Pending"),
                    ("unknown", "Unknown"),
                    ("absent_final", "Absent final"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="request_subject_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="result_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="idempotencyrecord",
            name="result_subject_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="financial_closure_status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("settlement_pending", "Settlement pending"),
                    ("closed", "Closed"),
                    ("reopened_for_adjustment", "Reopened for adjustment"),
                ],
                default="open",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="legacy_read_only",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="occupancy_status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("handover_pending", "Handover pending"),
                    ("occupied", "Occupied"),
                    ("move_out_pending", "Move-out pending"),
                    ("returned", "Returned"),
                    ("handover_disputed", "Handover disputed"),
                ],
                default="not_started",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="lease",
            name="tenancy_root_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="lease",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_signatures", "Pending signatures"),
                    ("pending", "Pending"),
                    ("signed", "Signed"),
                    ("active", "Active"),
                    ("termination_pending", "Termination pending"),
                    ("ended", "Ended"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rentinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("due", "Due"),
                    ("overdue", "Overdue"),
                    ("partially_paid", "Partially paid"),
                    ("paid", "Paid"),
                    ("settled", "Settled"),
                    ("cancelled", "Cancelled"),
                    ("written_off", "Written off"),
                ],
                default="due",
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="lease",
            name="unique_live_lease_per_accommodation",
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    status__in=[
                        "draft",
                        "pending_signatures",
                        "pending",
                        "signed",
                        "active",
                        "termination_pending",
                    ]
                ),
                fields=("property", "offer_id"),
                name="unique_live_lease_per_accommodation",
            ),
        ),
    ]
