# Generated by Django 4.2.11 on 2026-10-09 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0020_propertyvisit_accepted_at"),
        ("features", "0003_idempotencyrecord_is_rental_operation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerOnboardingSession",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_key", models.UUIDField()),
                ("profile_revision", models.PositiveIntegerField()),
                ("provider_session_id", models.CharField(max_length=120)),
                ("hosted_url", models.URLField(max_length=500)),
                ("status", models.CharField(default="created", max_length=20)),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="OwnerPaymentProfile",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not started"),
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("restricted", "Restricted"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("provider", models.CharField(default="", max_length=40)),
                (
                    "provider_account_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("masked_beneficiary", models.JSONField(blank=True, default=dict)),
                ("requirements", models.JSONField(blank=True, default=list)),
                (
                    "accepted_policy_versions",
                    models.JSONField(blank=True, default=list),
                ),
                ("payout_ready", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalCommercialPolicy",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(max_length=40, unique=True)),
                ("commission_rate_bps", models.PositiveIntegerField(default=1000)),
                ("commission_payer", models.CharField(default="owner", max_length=20)),
                (
                    "commission_basis",
                    models.CharField(default="first_period_base_rent", max_length=40),
                ),
                (
                    "processing_fee_payer",
                    models.CharField(default="platform", max_length=20),
                ),
                ("renewal_commission_rate_bps", models.PositiveIntegerField(default=0)),
                ("timezone", models.CharField(default="Africa/Cairo", max_length=40)),
                ("billing_cycle", models.CharField(default="monthly", max_length=20)),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                ("summary", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalInterest",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("offer_id", models.CharField(max_length=64)),
                ("offer_revision", models.PositiveIntegerField()),
                ("offer_snapshot", models.JSONField()),
                ("desired_start", models.DateField()),
                ("months", models.PositiveSmallIntegerField()),
                ("occupants", models.PositiveSmallIntegerField(default=1)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                            ("proposed", "Proposed"),
                            ("invited", "Invited"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RentalInventoryDayLock",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("offer_id", models.CharField(max_length=64)),
                ("stay_on", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("hold", "Hold"), ("occupied", "Occupied")],
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RentalTimelineEvent",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True, default="")),
                ("resource_id", models.UUIDField(blank=True, null=True)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TermsProposal",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("changes_requested", "Changes requested"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="proposed",
                        max_length=24,
                    ),
                ),
                ("terms", models.JSONField()),
                ("previous_terms", models.JSONField(blank=True, default=list)),
                ("offer_snapshot", models.JSONField()),
                ("accepted_by", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="lease",
            name="unique_live_lease_per_accommodation",
        ),
        migrations.AddField(
            model_name="lease",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="document_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="lease",
            name="document_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="hold_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lease",
            name="policy_version",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="lease",
            name="reviewed_by",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lease",
            name="terms",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="signingsession",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signingsession",
            name="document_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="signingsession",
            name="document_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="signingsession",
            name="lease_revision",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="signingsession",
            name="provider_session_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="signingsession",
            name="request_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="consumed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="eligibility_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name="lease",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("legacy_read_only", True),
                    (
                        "status__in",
                        [
                            "draft",
                            "pending_signatures",
                            "pending",
                            "signed",
                            "active",
                            "termination_pending",
                        ],
                    ),
                ),
                fields=("property", "offer_id"),
                name="unique_live_lease_per_accommodation",
            ),
        ),
        migrations.AddField(
            model_name="termsproposal",
            name="interest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="terms_proposals",
                to="features.rentalinterest",
            ),
        ),
        migrations.AddField(
            model_name="termsproposal",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_terms_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentaltimelineevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rental_timeline_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rentaltimelineevent",
            name="lease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="features.lease",
            ),
        ),
        migrations.AddField(
            model_name="rentalinventorydaylock",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_day_locks",
                to="features.lease",
            ),
        ),
        migrations.AddField(
            model_name="rentalinventorydaylock",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_day_locks",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="rentalinterest",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_interests",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="rentalinterest",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_interests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ownerpaymentprofile",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_payment_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="owneronboardingsession",
            name="owner_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="onboarding_sessions",
                to="features.ownerpaymentprofile",
            ),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="features.rentalinterest",
            ),
        ),
        migrations.AddField(
            model_name="tenancyinvitation",
            name="terms_proposal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="features.termsproposal",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalinventorydaylock",
            constraint=models.UniqueConstraint(
                fields=("property", "offer_id", "stay_on"),
                name="unique_rental_offer_stay_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalinterest",
            constraint=models.CheckConstraint(
                check=models.Q(("revision__gte", 1)),
                name="rental_interest_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalinterest",
            constraint=models.CheckConstraint(
                check=models.Q(("months__gte", 1)),
                name="rental_interest_months_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="owneronboardingsession",
            constraint=models.UniqueConstraint(
                fields=("owner_profile", "request_key"),
                name="unique_owner_onboarding_request",
            ),
        ),
    ]
