# Generated by Django 4.2.11 on 2026-10-09 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("features", "0005_seed_rental_policy_v1"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPeriod",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("start", models.DateField()),
                ("end_exclusive", models.DateField()),
                ("issue_at", models.DateTimeField()),
                ("due_at", models.DateTimeField()),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_periods",
                        to="features.lease",
                    ),
                ),
            ],
            options={
                "ordering": ["start", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="PaymentAttempt",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_key", models.UUIDField()),
                ("revision", models.PositiveIntegerField(default=1)),
                ("invoice_revision", models.PositiveIntegerField()),
                ("policy_version", models.CharField(max_length=40)),
                ("quote_fingerprint", models.CharField(max_length=64)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("pending", "Pending"),
                            ("authorized", "Authorized"),
                            ("captured", "Captured"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "settlement_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("payout_status", models.CharField(default="held", max_length=24)),
                (
                    "provider_attempt_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, default="", max_length=80),
                ),
            ],
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="navigation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="provider_session_id",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="request_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="return_state",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="applied_minor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="charges_minor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="credits_minor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="deferred_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="invoice_type",
            field=models.CharField(
                choices=[
                    ("rent", "Rent"),
                    ("deposit", "Deposit"),
                    ("adjustment", "Adjustment"),
                ],
                default="rent",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="period_end_exclusive",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="period_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="receipt_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProviderWebhookEvent",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(max_length=40)),
                ("provider_event_id", models.CharField(max_length=120)),
                ("event_type", models.CharField(max_length=60)),
                ("sequence", models.PositiveBigIntegerField(default=0)),
                ("payload_digest", models.CharField(max_length=64)),
                ("signature_valid", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provider_events",
                        to="features.paymentattempt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentReceipt",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="ready", max_length=20)),
                (
                    "title",
                    models.CharField(default="Rent payment receipt", max_length=160),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "payment_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt",
                        to="features.paymentattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaymentQuote",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_key", models.UUIDField()),
                ("invoice_revision", models.PositiveIntegerField()),
                ("payer_amount_minor", models.PositiveBigIntegerField()),
                ("tenant_service_fee_minor", models.PositiveBigIntegerField(default=0)),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                ("policy_version", models.CharField(max_length=40)),
                ("fingerprint", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_quotes",
                        to="features.rentinvoice",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_attempts",
                to="features.rentinvoice",
            ),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="payer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rental_payment_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_attempts",
                to="features.paymentquote",
            ),
        ),
        migrations.CreateModel(
            name="OwnerPayable",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("gross_minor", models.PositiveBigIntegerField()),
                ("commission_minor", models.PositiveBigIntegerField(default=0)),
                ("processing_fee_minor", models.PositiveBigIntegerField(default=0)),
                ("net_minor", models.PositiveBigIntegerField()),
                (
                    "settlement_status",
                    models.CharField(default="pending", max_length=20),
                ),
                (
                    "payout_status",
                    models.CharField(default="pending_eligibility", max_length=24),
                ),
                ("blocking_reasons", models.JSONField(blank=True, default=list)),
                (
                    "billing_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_payables",
                        to="features.billingperiod",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_payable",
                        to="features.rentinvoice",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_payables",
                        to="features.lease",
                    ),
                ),
                (
                    "payment_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owner_payable",
                        to="features.paymentattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=120, unique=True)),
                ("kind", models.CharField(max_length=40)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_transactions",
                        to="features.rentinvoice",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_transactions",
                        to="features.lease",
                    ),
                ),
                (
                    "payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_transactions",
                        to="features.paymentattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account", models.CharField(max_length=60)),
                (
                    "direction",
                    models.CharField(
                        choices=[("debit", "Debit"), ("credit", "Credit")],
                        max_length=10,
                    ),
                ),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="features.ledgertransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoicePaymentAllocation",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_minor", models.PositiveBigIntegerField()),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_allocations",
                        to="features.rentinvoice",
                    ),
                ),
                (
                    "payment_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_allocation",
                        to="features.paymentattempt",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("line_type", models.CharField(max_length=40)),
                ("description", models.CharField(max_length=255)),
                ("amount_minor", models.BigIntegerField()),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                ("source", models.JSONField(blank=True, default=dict)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="features.rentinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="attempt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkout_session",
                to="features.paymentattempt",
            ),
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="quote",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checkout_sessions",
                to="features.paymentquote",
            ),
        ),
        migrations.AddField(
            model_name="rentinvoice",
            name="billing_period",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice",
                to="features.billingperiod",
            ),
        ),
        migrations.AddConstraint(
            model_name="providerwebhookevent",
            constraint=models.UniqueConstraint(
                fields=("provider", "provider_event_id"),
                name="unique_provider_webhook_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentquote",
            constraint=models.UniqueConstraint(
                fields=("invoice", "request_key"), name="unique_invoice_quote_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                fields=("payer", "invoice", "request_key"),
                name="unique_payment_attempt_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("payment_status__in", ["created", "pending", "authorized"])
                ),
                fields=("invoice",),
                name="unique_live_invoice_payment_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingperiod",
            constraint=models.UniqueConstraint(
                fields=("lease", "sequence"), name="unique_lease_billing_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="billingperiod",
            constraint=models.UniqueConstraint(
                fields=("lease", "start", "end_exclusive"),
                name="unique_lease_billing_period",
            ),
        ),
    ]
