# Generated by Django 4.2.11 on 2026-10-09 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("features", "0006_billingperiod_paymentattempt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutBatch",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("request_key", models.UUIDField(unique=True)),
                (
                    "provider_batch_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_payout_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalEvidence",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_key", models.UUIDField()),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=80)),
                ("size_bytes", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("storage_provider", models.CharField(default="fake", max_length=40)),
                ("storage_key", models.CharField(max_length=255, unique=True)),
                ("private_content", models.BinaryField(blank=True, null=True)),
                (
                    "malware_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("safe", "Safe"),
                            ("unsafe", "Unsafe"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("retain_until", models.DateField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence",
                        to="features.lease",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalPayout",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                ("masked_beneficiary", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("processing", "Processing"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("held", "Held"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "provider_payout_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "hold_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "failure_code",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="features.payoutbatch",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="features.lease",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payables",
                    models.ManyToManyField(
                        related_name="payouts", to="features.ownerpayable"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RentalHandover",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("move_in", "Move in"), ("move_out", "Move out")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending approval"),
                            ("accepted", "Accepted"),
                            ("disputed", "Disputed"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("possession_on", models.DateField()),
                ("condition", models.JSONField(default=dict)),
                ("keys", models.JSONField(default=dict)),
                ("meters", models.JSONField(default=dict)),
                ("inventory", models.JSONField(default=list)),
                ("approvals", models.JSONField(default=list)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "evidence",
                    models.ManyToManyField(
                        blank=True,
                        related_name="handovers",
                        to="features.rentalevidence",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handovers",
                        to="features.lease",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PayoutAuditEvent",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=40)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payout_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="features.rentalpayout",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DepositAgreement",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("agreed_minor", models.PositiveBigIntegerField(default=0)),
                ("due_minor", models.PositiveBigIntegerField(default=0)),
                ("collected_minor", models.PositiveBigIntegerField(default=0)),
                ("returned_minor", models.PositiveBigIntegerField(default=0)),
                ("applied_minor", models.PositiveBigIntegerField(default=0)),
                ("disputed_minor", models.PositiveBigIntegerField(default=0)),
                ("currency", models.CharField(default="EGP", max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_agreement",
                        to="features.rentinvoice",
                    ),
                ),
                (
                    "lease",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposit_agreement",
                        to="features.lease",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="rentalhandover",
            constraint=models.UniqueConstraint(
                fields=("lease", "kind"), name="unique_lease_handover_kind"
            ),
        ),
        migrations.AddConstraint(
            model_name="rentalevidence",
            constraint=models.UniqueConstraint(
                fields=("uploader", "lease", "request_key"),
                name="unique_rental_evidence_request",
            ),
        ),
    ]
