# Generated by Django 4.2.11 on 2026-10-09 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("features", "0007_payoutbatch_rentalevidence_rentalpayout_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalChange",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("payment_extension", "Payment extension"),
                            ("amendment", "Amendment"),
                            ("renewal", "Renewal"),
                            ("termination", "Termination"),
                            ("external_payment", "External payment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("changes_requested", "Changes requested"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("pending_signatures", "Pending signatures"),
                            ("signed", "Signed"),
                            ("applied", "Applied"),
                            ("review_required", "Operations review required"),
                        ],
                        default="proposed",
                        max_length=30,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField(blank=True, default="")),
                ("requested_date", models.DateField(blank=True, null=True)),
                ("original_due_at", models.DateTimeField(blank=True, null=True)),
                ("deferred_until", models.DateTimeField(blank=True, null=True)),
                ("effective_on", models.DateField(blank=True, null=True)),
                ("amount_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("method", models.CharField(blank=True, default="", max_length=40)),
                ("terms", models.JSONField(blank=True, default=dict)),
                ("previous_terms", models.JSONField(blank=True, default=dict)),
                ("approvals", models.JSONField(blank=True, default=list)),
                ("document_id", models.UUIDField(blank=True, null=True)),
                (
                    "document_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("signed_by", models.JSONField(blank=True, default=list)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "evidence",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rental_changes",
                        to="features.rentalevidence",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_changes",
                        to="features.rentinvoice",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_changes",
                        to="features.lease",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requested_rental_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_lease",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_rental_change",
                        to="features.lease",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=40)),
                ("priority", models.CharField(max_length=20)),
                ("access_times", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("acknowledged", "Acknowledged"),
                            ("appointment_proposed", "Appointment proposed"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In progress"),
                            ("resolution_reported", "Resolution reported"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=30,
                    ),
                ),
                ("appointment_at", models.DateTimeField(blank=True, null=True)),
                (
                    "proposed_cost_minor",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("cost_version", models.PositiveIntegerField(default=0)),
                (
                    "approved_cost_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("cost_payer", models.CharField(blank=True, default="", max_length=10)),
                (
                    "evidence",
                    models.ManyToManyField(
                        blank=True,
                        related_name="maintenance_requests",
                        to="features.rentalevidence",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_requests",
                        to="features.lease",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reported_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MaintenanceEvent",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(max_length=40)),
                ("note", models.TextField(blank=True, default="")),
                ("appointment_at", models.DateTimeField(blank=True, null=True)),
                ("cost_minor", models.PositiveBigIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "maintenance_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="features.maintenancerequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChangeSigningSession",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_key", models.UUIDField()),
                ("change_revision", models.PositiveIntegerField()),
                ("document_id", models.UUIDField()),
                ("document_hash", models.CharField(max_length=64)),
                ("provider_session_id", models.CharField(max_length=120, unique=True)),
                ("hosted_url", models.URLField(max_length=500)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("expires_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "change",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signing_sessions",
                        to="features.rentalchange",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rental_change_signing_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="changesigningsession",
            constraint=models.UniqueConstraint(
                fields=("change", "signer", "request_key"),
                name="unique_change_signing_request",
            ),
        ),
    ]
