from django.urls import path

from . import views
from . import rental_phase2_views as views_phase2
from . import rental_phase3_views as views_phase3
from . import rental_phase4_views as views_phase4
from . import rental_phase5_views as views_phase5
from . import rental_phase6_views as views_phase6
from .models import RentalChange

urlpatterns = [
    path(
        "rental-capabilities/",
        views.rental_capabilities,
        name="rental-capabilities",
    ),
    path(
        "rental-operations/<uuid:request_key>/",
        views.rental_operation_lookup,
        name="rental-operation-lookup",
    ),
    path("configuration/", views.configuration, name="feature-configuration"),
    path("boost-campaigns/", views.boost_campaigns, name="boost-campaigns"),
    path("search-alerts/", views.search_alerts, name="search-alerts"),
    path(
        "search-alerts/<uuid:alert_id>/",
        views.search_alert_detail,
        name="search-alert-detail",
    ),
    path(
        "owner-analytics/<uuid:property_id>/",
        views.owner_analytics,
        name="owner-analytics",
    ),
    path("listing-suggestions/", views.listing_suggestions, name="listing-suggestions"),
    path("lease-configuration/", views.lease_configuration, name="lease-configuration"),
    path(
        "owner-payment-profile/",
        views_phase2.owner_payment_profile,
        name="owner-payment-profile",
    ),
    path(
        "owner-payment-profile/onboarding-session/",
        views_phase2.owner_onboarding_session,
        name="owner-onboarding-session",
    ),
    path("rental-interests/", views_phase2.rental_interests, name="rental-interests"),
    path(
        "rental-interests/<uuid:interest_id>/",
        views_phase2.rental_interest_detail,
        name="rental-interest-detail",
    ),
    path(
        "rental-interests/<uuid:interest_id>/respond/",
        views_phase2.rental_interest_respond,
        name="rental-interest-respond",
    ),
    path("terms-proposals/", views_phase2.terms_proposals, name="terms-proposals"),
    path(
        "terms-proposals/<uuid:proposal_id>/",
        views_phase2.terms_proposal_detail,
        name="terms-proposal-detail",
    ),
    path(
        "terms-proposals/<uuid:proposal_id>/respond/",
        views_phase2.terms_proposal_respond,
        name="terms-proposal-respond",
    ),
    path("lease-tenants/", views.lease_tenants, name="lease-tenants"),
    path("tenancy-invitations/", views.tenancy_invitations, name="tenancy-invitations"),
    path(
        "tenancy-invitations/<uuid:invitation_id>/",
        views.tenancy_invitation_detail,
        name="tenancy-invitation-detail",
    ),
    path(
        "tenancy-invitations/<uuid:invitation_id>/respond/",
        views.tenancy_invitation_respond,
        name="tenancy-invitation-respond",
    ),
    path(
        "tenancy-invitations/<uuid:invitation_id>/revoke/",
        views_phase2.tenancy_invitation_revoke,
        name="tenancy-invitation-revoke",
    ),
    path("leases/", views.leases, name="leases"),
    path("leases/<uuid:lease_id>/", views.lease_detail, name="lease-detail"),
    path(
        "leases/<uuid:lease_id>/signing-session/",
        views.lease_signing_session,
        name="lease-signing-session",
    ),
    path(
        "leases/<uuid:lease_id>/review/",
        views_phase2.lease_review,
        name="lease-review",
    ),
    path(
        "leases/<uuid:lease_id>/submit-for-signature/",
        views_phase2.lease_submit_for_signature,
        name="lease-submit-for-signature",
    ),
    path(
        "leases/<uuid:lease_id>/timeline/",
        views_phase2.lease_timeline,
        name="lease-timeline",
    ),
    path(
        "leases/<uuid:lease_id>/billing-schedule/",
        views_phase2.lease_billing_schedule,
        name="lease-billing-schedule",
    ),
    path(
        "provider-webhooks/rental/",
        views_phase2.fake_rental_provider_webhook,
        name="fake-rental-provider-webhook",
    ),
    path("leases/<uuid:lease_id>/cancel/", views.lease_cancel, name="lease-cancel"),
    path("rent-invoices/", views.rent_invoices, name="rent-invoices"),
    path(
        "rent-invoices/<uuid:invoice_id>/",
        views.rent_invoice_detail,
        name="rent-invoice-detail",
    ),
    path(
        "rent-invoices/<uuid:invoice_id>/checkout/",
        views_phase3.rent_invoice_checkout,
        name="rent-invoice-checkout",
    ),
    path("rent-invoices/<uuid:invoice_id>/quote/", views_phase3.rent_invoice_quote, name="rent-invoice-quote"),
    path("payment-attempts/", views_phase3.payment_attempts, name="payment-attempts"),
    path("payment-attempts/<uuid:attempt_id>/", views_phase3.payment_attempt_detail, name="payment-attempt-detail"),
    path("payment-attempts/<uuid:attempt_id>/reconcile/", views_phase3.payment_attempt_reconcile, name="payment-attempt-reconcile"),
    path("owner-payables/", views_phase3.owner_payables, name="owner-payables"),
    path("provider-webhooks/payments/", views_phase3.fake_payment_webhook, name="fake-payment-webhook"),
    path("leases/<uuid:lease_id>/handovers/", views_phase4.lease_handovers, name="lease-handovers"),
    path("handovers/<uuid:handover_id>/", views_phase4.handover_detail, name="handover-detail"),
    path("handovers/<uuid:handover_id>/respond/", views_phase4.handover_respond, name="handover-respond"),
    path("rental-attachments/", views_phase4.rental_evidence_upload, name="rental-evidence-upload"),
    path("rental-attachments/<uuid:evidence_id>/", views_phase4.rental_evidence_detail, name="rental-evidence-detail"),
    path("rental-attachments/<uuid:evidence_id>/download/", views_phase4.rental_evidence_download, name="rental-evidence-download"),
    path("leases/<uuid:lease_id>/deposit/", views_phase4.lease_deposit, name="lease-deposit"),
    path("payouts/", views_phase4.payouts, name="rental-payouts"),
    path("payouts/<uuid:payout_id>/", views_phase4.payout_detail, name="rental-payout-detail"),
    path("operations/payouts/execute/", views_phase4.operations_execute_payout, name="operations-payout-execute"),
    path("operations/payouts/<uuid:payout_id>/reconcile/", views_phase4.operations_reconcile_payout, name="operations-payout-reconcile"),
    path("leases/<uuid:lease_id>/maintenance-requests/", views_phase5.maintenance_requests, name="maintenance-requests"),
    path("maintenance-requests/<uuid:request_id>/", views_phase5.maintenance_detail, name="maintenance-detail"),
    path("maintenance-requests/<uuid:request_id>/actions/", views_phase5.maintenance_action, name="maintenance-action"),
    path("leases/<uuid:lease_id>/payment-extension-requests/", views_phase5.payment_extensions, name="payment-extensions"),
    path("leases/<uuid:lease_id>/amendments/", views_phase5.amendments, name="amendments"),
    path("leases/<uuid:lease_id>/renewals/", views_phase5.renewals, name="renewals"),
    path("leases/<uuid:lease_id>/termination-requests/", views_phase5.terminations, name="terminations"),
    path("rent-invoices/<uuid:invoice_id>/external-payment-claims/", views_phase5.external_claim_create, name="external-claim-create"),
    path("leases/<uuid:lease_id>/external-payment-claims/", views_phase5.external_claims, name="external-claims"),
    path("payment-extension-requests/<uuid:change_id>/", views_phase5.change_detail, {"kind": RentalChange.Kind.PAYMENT_EXTENSION}, name="payment-extension-detail"),
    path("payment-extension-requests/<uuid:change_id>/respond/", views_phase5.change_respond, {"kind": RentalChange.Kind.PAYMENT_EXTENSION}, name="payment-extension-respond"),
    path("amendments/<uuid:change_id>/", views_phase5.change_detail, {"kind": RentalChange.Kind.AMENDMENT}, name="amendment-detail"),
    path("amendments/<uuid:change_id>/respond/", views_phase5.change_respond, {"kind": RentalChange.Kind.AMENDMENT}, name="amendment-respond"),
    path("amendments/<uuid:change_id>/submit-for-signature/", views_phase5.submit_change_for_signature, {"kind": RentalChange.Kind.AMENDMENT}, name="amendment-submit"),
    path("amendments/<uuid:change_id>/signing-session/", views_phase5.change_signing_session, {"kind": RentalChange.Kind.AMENDMENT}, name="amendment-signing"),
    path("renewals/<uuid:change_id>/", views_phase5.change_detail, {"kind": RentalChange.Kind.RENEWAL}, name="renewal-detail"),
    path("renewals/<uuid:change_id>/respond/", views_phase5.change_respond, {"kind": RentalChange.Kind.RENEWAL}, name="renewal-respond"),
    path("renewals/<uuid:change_id>/submit-for-signature/", views_phase5.submit_change_for_signature, {"kind": RentalChange.Kind.RENEWAL}, name="renewal-submit"),
    path("renewals/<uuid:change_id>/signing-session/", views_phase5.change_signing_session, {"kind": RentalChange.Kind.RENEWAL}, name="renewal-signing"),
    path("termination-requests/<uuid:change_id>/", views_phase5.change_detail, {"kind": RentalChange.Kind.TERMINATION}, name="termination-detail"),
    path("termination-requests/<uuid:change_id>/respond/", views_phase5.change_respond, {"kind": RentalChange.Kind.TERMINATION}, name="termination-respond"),
    path("external-payment-claims/<uuid:change_id>/", views_phase5.change_detail, {"kind": RentalChange.Kind.EXTERNAL_PAYMENT}, name="external-claim-detail"),
    path("external-payment-claims/<uuid:change_id>/respond/", views_phase5.change_respond, {"kind": RentalChange.Kind.EXTERNAL_PAYMENT}, name="external-claim-respond"),
    path("leases/<uuid:lease_id>/final-settlement/", views_phase6.final_settlement_detail, name="final-settlement"),
    path("leases/<uuid:lease_id>/final-settlement/propose/", views_phase6.final_settlement_propose, name="final-settlement-propose"),
    path("leases/<uuid:lease_id>/final-settlement/respond/", views_phase6.final_settlement_respond, name="final-settlement-respond"),
    path("refund-requests/", views_phase6.refund_requests, name="refund-requests"),
    path("refund-requests/<uuid:refund_id>/", views_phase6.refund_detail, name="refund-detail"),
    path("refund-requests/<uuid:refund_id>/respond/", views_phase6.refund_respond, name="refund-respond"),
    path("disputes/", views_phase6.disputes, name="rental-disputes"),
    path("disputes/<uuid:dispute_id>/", views_phase6.dispute_detail, name="rental-dispute-detail"),
    path("disputes/<uuid:dispute_id>/respond/", views_phase6.dispute_respond, name="rental-dispute-respond"),
    path("leases/<uuid:lease_id>/documents/", views_phase6.lease_documents, name="lease-documents"),
    path("rental-documents/<uuid:document_id>/download/", views_phase6.document_download, name="rental-document-download"),
    path("rental-statements/", views_phase6.rental_statement_create, name="rental-statement-create"),
    path("leases/<uuid:lease_id>/reviews/", views_phase6.lease_reviews, name="lease-reviews"),
    path("leases/<uuid:lease_id>/rental-center/", views_phase6.rental_center, name="rental-center"),
]
