# Generated by Django 4.2.11 on 2026-07-16 20:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_add_kyc_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="confirmation_selfi",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Confirmation Selfie",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_back",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="ID Back"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id_face",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="ID Face"
            ),
        ),
    ]
