# Generated by Django 4.2.11 on 2026-07-18

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_profile_avatar_alter_profile_confirmation_selfi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="", max_length=128, verbose_name="Phone Number"
            ),
        ),
    ]
