name: melos_core
environment:
  sdk: ^3.9.0
resolution: workspace
dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  flutter_local_notifications: ^19.4.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  multiple_result: ^5.2.0
  flutter_svg: ^2.3.0
  internet_connection_checker: ^3.0.1
  injectable: ^2.5.0
  easy_localization:
  dio: ^5.9.2
  dio_cookie_manager: 3.5.0
  cookie_jar: ^4.0.9
  lottie: ^3.3.3
  permission_handler: ^12.0.3
  flutter_spinkit: ^5.2.2
  top_snackbar_flutter: ^3.3.0
  toastification: ^3.0.3
  timezone: ^0.10.1
  objectbox: ^4.0.3
  objectbox_flutter_libs: ^4.0.3
  image_picker: ^1.2.2
  image_cropper: ^12.2.1
  connectivity_plus: ^6.1.5
  url_launcher: ^6.3.2
  socket_io_client: ^3.1.6
  shared_preferences: ^2.5.5
  share_plus: ^12.0.2
  safe_text: ^2.1.6
  pinput: ^6.0.2
  pinch_zoom: ^2.0.1
  path_provider: ^2.1.5
  package_info_plus: ^8.3.0
  intl: ^0.20.2
  hydrated_bloc: ^11.0.0
  get_it: ^9.2.1
  flutter_secure_storage: ^10.3.1
  flutter_phoenix: ^1.1.1
  cached_network_image: ^3.4.1
  easy_loading_button: ^0.4.0
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  cloud_firestore: ^6.6.0
  pagify: ^0.3.2
  dropinity: ^0.0.1
  nsfw_detector_flutter: ^2.0.0
  appsflyer_sdk: ^6.18.0
  vector_graphics: ^1.2.2

dependency_overrides:
  connectivity_plus: ^6.1.5

dev_dependencies:
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  objectbox_generator: ^4.1.0

flutter:
  assets:
    - assets/translations/
    - assets/lottie/
    - assets/fonts/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 900
    - family: Riyal
      fonts:
        - asset: assets/fonts/riyal.ttf
flutter_assets_generator:
  output_dir: generated/
  output_filename: assets
  class_name: Assets
  auto_detection: true
  # Automatically add missing dependencies (rive, flutter_svg, lottie) default: true
  auto_add_dependencies: true
  # Options: robust (default), legacy (old style)
  style: robust
  package_parameter_enabled: false
  named_with_parent: true
  path_ignore: [ ]
