# Generated by Django 4.2.11 on 2026-07-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="suitable_for",
            field=models.CharField(
                choices=[
                    ("families", "Families"),
                    ("singles", "Singles"),
                    ("students", "Students"),
                    ("female_students", "Female Students Only"),
                    ("all", "All"),
                ],
                default="all",
                max_length=50,
                verbose_name="Suitable For",
            ),
        ),
    ]
