# Generated by Django 4.2.11 on 2026-09-29 16:30

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0016_alter_property_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Property Video",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="video_duration",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Video Duration (seconds)",
            ),
        ),
    ]
