# Generated by Django 4.2.11 on 2026-10-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0018_property_mobile_handoff"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="savedproperty",
            name="unique_saved_property",
        ),
        migrations.AddField(
            model_name="property",
            name="availability_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="rental_inventory",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="property",
            name="rental_min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="rental_price_period",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="property",
            name="rental_scopes",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="propertyvisit",
            name="offer_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="propertyvisit",
            name="offer_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="savedproperty",
            name="offer_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="savedproperty",
            name="offer_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Price"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedproperty",
            constraint=models.UniqueConstraint(
                fields=("user", "property", "offer_id"),
                name="unique_saved_property_offer",
            ),
        ),
    ]
