# Generated by Django 4.2.11 on 2026-10-08 15:53

from django.db import migrations, models


def backfill_visit_acceptance(apps, schema_editor):
    PropertyVisit = apps.get_model("properties", "PropertyVisit")
    Notification = apps.get_model("notifications", "Notification")
    PropertyVisit.objects.filter(status="confirmed", accepted_at__isnull=True).update(
        accepted_at=models.F("updated_at")
    )
    for notification in Notification.objects.filter(
        notification_type="visit_accepted"
    ).iterator():
        visit_id = (notification.data or {}).get("visit_id")
        if visit_id:
            PropertyVisit.objects.filter(
                id=visit_id, accepted_at__isnull=True
            ).update(accepted_at=notification.created_at)


def clear_visit_acceptance(apps, schema_editor):
    PropertyVisit = apps.get_model("properties", "PropertyVisit")
    PropertyVisit.objects.update(accepted_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_notification_type"),
        ("properties", "0019_remove_savedproperty_unique_saved_property_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyvisit",
            name="accepted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_visit_acceptance, clear_visit_acceptance),
    ]
