name: landing_page
environment:
  sdk: ^3.9.0
resolution: workspace


dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.8
  melos_core:
    path: ../../packages/core


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
flutter_assets_generator:
  output_dir: generated/
  output_filename: assets
  class_name: Assets
  auto_detection: true
  # Automatically add missing dependencies (rive, flutter_svg, lottie) default: true
  auto_add_dependencies: true
  # Options: robust (default), legacy (old style)
  style: robust
  package_parameter_enabled: false
  named_with_parent: true
  path_ignore: [ ]
