# Generated by Django 4.2.11 on 2026-09-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_rename_devtok_user_active_idx_notificatio_user_id_f0e72c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at", "-pkid"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
    ]
