# Generated by Django 4.2.11 on 2025-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
