# Generated by Django 4.2.11 on 2026-09-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="message",
            new_name="chat_messag_convers_3154fc_idx",
            old_name="chat_message_conv_created_idx",
        ),
    ]
