# Generated by Django 4.2.11 on 2026-10-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0002_rename_chat_message_conv_created_idx_chat_messag_convers_3154fc_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client_message_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("conversation", "sender", "client_message_id"),
                name="unique_chat_client_message_id",
            ),
        ),
    ]
