name: aait_flutter_app
environment:
  sdk: ^3.9.0
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.8
  flutter_bloc: ^9.1.1
  rename: ^3.1.0
  change_app_package_name: ^1.5.0
  flutter_screenutil: ^5.9.3

  firebase_core: ^4.3.0
  firebase_remote_config: ^6.2.0
  cloud_firestore: ^6.5.0

  melos_core:
    path: ../../packages/core

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
flutter_assets_generator:
  output_dir: generated/
  output_filename: assets
  class_name: Assets
  auto_detection: true
  # Automatically add missing dependencies (rive, flutter_svg, lottie) default: true
  auto_add_dependencies: true
  # Options: robust (default), legacy (old style)
  style: robust
  package_parameter_enabled: false
  named_with_parent: true
  path_ignore: [ ]
