# Generated by Django 4.2.11 on 2026-07-16 21:36

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "price_period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Price Period",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("villa", "Villa"),
                            ("studio", "Studio"),
                            ("penthouse", "Penthouse"),
                        ],
                        default="apartment",
                        max_length=20,
                        verbose_name="Property Type",
                    ),
                ),
                (
                    "is_furnished",
                    models.BooleanField(default=False, verbose_name="Is Furnished"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Is Verified"),
                ),
                ("bedrooms", models.IntegerField(default=1, verbose_name="Bedrooms")),
                ("bathrooms", models.IntegerField(default=1, verbose_name="Bathrooms")),
                ("area", models.IntegerField(default=0, verbose_name="Area (sqm)")),
                (
                    "floor",
                    models.IntegerField(blank=True, null=True, verbose_name="Floor"),
                ),
                (
                    "rental_period",
                    models.IntegerField(
                        default=1, verbose_name="Rental Period (months)"
                    ),
                ),
                (
                    "suitable_for",
                    models.CharField(
                        choices=[
                            ("families", "Families"),
                            ("singles", "Singles"),
                            ("students", "Students"),
                            ("all", "All"),
                        ],
                        default="all",
                        max_length=50,
                        verbose_name="Suitable For",
                    ),
                ),
                (
                    "smoking_allowed",
                    models.BooleanField(default=False, verbose_name="Smoking Allowed"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Egypt", max_length=100, verbose_name="Country"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                ("district", models.CharField(max_length=100, verbose_name="District")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "has_wifi",
                    models.BooleanField(default=False, verbose_name="Has Wi-Fi"),
                ),
                (
                    "has_elevator",
                    models.BooleanField(default=False, verbose_name="Has Elevator"),
                ),
                (
                    "has_garage",
                    models.BooleanField(default=False, verbose_name="Has Garage"),
                ),
                (
                    "has_security",
                    models.BooleanField(default=False, verbose_name="Has Security"),
                ),
                (
                    "has_balcony",
                    models.BooleanField(default=False, verbose_name="Has Balcony"),
                ),
                (
                    "has_air_conditioning",
                    models.BooleanField(
                        default=False, verbose_name="Has Air Conditioning"
                    ),
                ),
                (
                    "near_metro",
                    models.BooleanField(default=False, verbose_name="Near Metro"),
                ),
                (
                    "has_natural_gas",
                    models.BooleanField(default=False, verbose_name="Has Natural Gas"),
                ),
                (
                    "has_electricity_meter",
                    models.BooleanField(
                        default=False, verbose_name="Has Electricity Meter"
                    ),
                ),
                (
                    "has_water_meter",
                    models.BooleanField(default=False, verbose_name="Has Water Meter"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="Property Image"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                        verbose_name="Property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Image",
                "verbose_name_plural": "Property Images",
            },
        ),
    ]
