# Generated by Django 4.2.11 on 2026-07-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_suitable_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyimage",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Name"
            ),
        ),
    ]
