# Generated by Django 4.2.11 on 2026-07-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_propertyimage_description_propertyimage_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["city", "district"], name="property_location_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["price"], name="property_price_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["-created_at"], name="property_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(
                fields=["property_type", "price"], name="property_type_price_idx"
            ),
        ),
    ]
