# Generated by Django 4.2.11 on 2026-07-16 22:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_property_property_location_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="main_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="Main Image"
            ),
        ),
    ]
