# Generated by Django 4.2.11 on 2026-07-16 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="space",
            field=models.CharField(
                blank=True, default="", max_length=50, verbose_name="Space"
            ),
        ),
    ]
