# Generated by Django 4.2.11 on 2026-07-17 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("properties", "0006_property_space"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyVisit",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visit_date", models.DateField(verbose_name="Visit Date")),
                ("visit_time", models.TimeField(verbose_name="Visit Time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="Note")),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="properties.property",
                        verbose_name="Property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Visit",
                "verbose_name_plural": "Property Visits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="propertyvisit",
            constraint=models.UniqueConstraint(
                fields=("tenant", "property", "visit_date", "visit_time"),
                name="unique_tenant_property_visit_slot",
            ),
        ),
    ]
