# Generated by Django 4.2.11 on 2026-09-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0015_owneravailabilityslot_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("under_review", "Under Review"),
                    ("needs_revision", "Needs Revision"),
                    ("hidden", "Hidden"),
                ],
                default="under_review",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
